### ISSUE TITLE
CIで違うプロジェクトがチェックされている？

### ISSUE THREAD

**Issue by TatsukiNishimura** [OUXT-Polaris/firmware#1]
自分の環境ではビルドするファイル数は1640だが、
![screenshot](https://user-images.githubusercontent.com/74486926/172007080-577e5074-b801-46be-bd15-d5a5aa1ac166.png)

CIでは254となっている。
![ci](https://user-images.githubusercontent.com/74486926/172007092-f34f7d86-3ab1-4dd5-aa7e-a67d367405f5.png)
となっている。
また、CI上でのプログラム名がmbed-os-example-blinkyとなっているので、
CIが走るたびにmbed-os-example-blinkyをビルドしているのでは？

**Comment by hakuturu583** [comment]
https://github.com/OUXT-Polaris/mbed-tcp/blob/9de8a0d4bf774a379b9e0da8e2412590610731f2/.github/workflows/buildtest.yml#L18-L19

この二行の削除おねがいします。

**Comment by hakuturu583** [comment]
#2 にて修正完了
